apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  labels:
    app: kafka-client
spec:
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
        - name: kafka-client
          image: docker.io/bitnami/kafka:2.6.0-debian-10-r57
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: kafka-zookeeper
